export const ACTION_TYPES={
    //----------------------------------------USER_ACTION_TYPES;

    USER_REGISTER_REQUEST:" USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS:" USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILED:" USER_REGISTER_FAILED",

    USER_LOGIN_REQUEST:" USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS:" USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILED:" USER_LOGIN_FAILED",

}